<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ObjectListView2022.ConsumerCompatibility.Current</AssemblyName>
    <RootNamespace>ObjectListViewConsumerCompatibility</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ObjectListView2022\ObjectListView2022.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Design" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
