using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace BrightIdeasSoftware
{
    public partial class OLVColumn
    {
        /// <summary>
        /// Gets or sets whether this aspect getter was generated internally.
        /// </summary>
        [Obsolete("This property is no longer maintained", true),
         Browsable(false),
         DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public bool AspectGetterAutoGenerated
        {
            get => aspectGetterAutoGenerated;
            set => aspectGetterAutoGenerated = value;
        }

        private bool aspectGetterAutoGenerated;
    }

    public partial class ObjectListView
    {
        /// <summary>
        /// Gets the list of columns used in tile view.
        /// </summary>
        [Browsable(false),
         Obsolete("Use GetFilteredColumns() and OLVColumn.IsTileViewColumn instead"),
         DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public List<OLVColumn> ColumnsForTileView => GetFilteredColumns(View.Tile);

        /// <summary>
        /// Gets or sets the font used by column headers.
        /// </summary>
        [DefaultValue(null)]
        [Browsable(false)]
        [Obsolete("Use a HeaderFormatStyle instead", false)]
        public Font HeaderFont
        {
            get => HeaderFormatStyle == null ? null : HeaderFormatStyle.Normal.Font;
            set
            {
                if (value == null && HeaderFormatStyle == null)
                {
                    return;
                }

                HeaderFormatStyle ??= new HeaderFormatStyle();
                HeaderFormatStyle.SetFont(value);
            }
        }

        /// <summary>
        /// Gets the index of the item currently under the cursor.
        /// </summary>
        [Browsable(false),
         Obsolete("Use HotRowIndex instead", false)]
        public virtual int HotItemIndex => HotRowIndex;

        /// <summary>
        /// Gets or sets the selected-row background color.
        /// </summary>
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [Obsolete("Use SelectedBackColor instead")]
        public virtual Color HighlightBackgroundColor
        {
            get => SelectedBackColor;
            set => SelectedBackColor = value;
        }

        /// <summary>
        /// Gets the effective selected-row background color.
        /// </summary>
        [Obsolete("Use SelectedBackColorOrDefault instead")]
        public virtual Color HighlightBackgroundColorOrDefault => SelectedBackColorOrDefault;

        /// <summary>
        /// Gets or sets the selected-row foreground color.
        /// </summary>
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [Obsolete("Use SelectedForeColor instead")]
        public virtual Color HighlightForegroundColor
        {
            get => SelectedForeColor;
            set => SelectedForeColor = value;
        }

        /// <summary>
        /// Gets the effective selected-row foreground color.
        /// </summary>
        [Obsolete("Use SelectedForeColorOrDefault instead")]
        public virtual Color HighlightForegroundColorOrDefault => SelectedForeColorOrDefault;

        /// <summary>
        /// Gets or sets the unfocused selected-row background color.
        /// </summary>
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [Obsolete("Use UnfocusedSelectedBackColor instead")]
        public virtual Color UnfocusedHighlightBackgroundColor
        {
            get => UnfocusedSelectedBackColor;
            set => UnfocusedSelectedBackColor = value;
        }

        /// <summary>
        /// Gets the effective unfocused selected-row background color.
        /// </summary>
        [Obsolete("Use UnfocusedSelectedBackColorOrDefault instead")]
        public virtual Color UnfocusedHighlightBackgroundColorOrDefault => UnfocusedSelectedBackColorOrDefault;

        /// <summary>
        /// Gets or sets the unfocused selected-row foreground color.
        /// </summary>
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [Obsolete("Use UnfocusedSelectedForeColor instead")]
        public virtual Color UnfocusedHighlightForegroundColor
        {
            get => UnfocusedSelectedForeColor;
            set => UnfocusedSelectedForeColor = value;
        }

        /// <summary>
        /// Gets the effective unfocused selected-row foreground color.
        /// </summary>
        [Obsolete("Use UnfocusedSelectedForeColorOrDefault instead")]
        public virtual Color UnfocusedHighlightForegroundColorOrDefault => UnfocusedSelectedForeColorOrDefault;

        /// <summary>
        /// Handles a header right click using the legacy no-argument hook.
        /// </summary>
        /// <returns>Always false, matching the ObjectListView 2.9.1 compatibility hook.</returns>
        [Obsolete("Use HandleHeaderRightClick(int) instead")]
        protected virtual bool HandleHeaderRightClick() => false;

        /// <summary>
        /// Shows the legacy column-selection menu at the given point.
        /// </summary>
        /// <param name="pt">The screen location at which to show the menu.</param>
        [Obsolete("Use ShowHeaderRightClickMenu instead")]
        protected virtual void ShowColumnSelectMenu(Point pt)
        {
            var menu = MakeColumnSelectMenu(new ContextMenuStrip());
            menu.Show(pt);
        }

        /// <summary>
        /// Gets the single selected model object, or null when the selection is not singular.
        /// </summary>
        [Obsolete("Use SelectedObject property instead of this method")]
        public virtual object GetSelectedObject() => SelectedObject;

        /// <summary>
        /// Gets the selected model objects as an ArrayList.
        /// </summary>
        [Obsolete("Use SelectedObjects property instead of this method")]
        public virtual ArrayList GetSelectedObjects() => EnumerableToArray(SelectedObjects, false);

        /// <summary>
        /// Gets the single checked model object, or null when the checked set is not singular.
        /// </summary>
        [Obsolete("Use CheckedObject property instead of this method")]
        public virtual object GetCheckedObject() => CheckedObject;

        /// <summary>
        /// Gets the checked model objects as an ArrayList.
        /// </summary>
        [Obsolete("Use CheckedObjects property instead of this method")]
        public virtual ArrayList GetCheckedObjects() => EnumerableToArray(CheckedObjects, false);

        /// <summary>
        /// Legacy compatibility hook for alternate row coloring.
        /// </summary>
        [Obsolete("This method is no longer used. Override PostProcessOneRow() to achieve a similar result")]
        protected virtual void PrepareAlternateBackColors()
        {
        }

        /// <summary>
        /// Legacy compatibility hook for native subitem-image setup.
        /// </summary>
        [Obsolete("This method is not longer maintained and will be removed", false)]
        protected virtual void SetAllSubItemImages()
        {
        }
    }
}
